"""Skill tree integrity: SKILL.md stays under the Agent Skills size guidance,
every path it and the flows point at exists, versions agree between SKILL.md
and CHANGELOG.md, and the bundle carries nothing claude.ai rejects."""
import os
import re
import unittest

from _paths import SKILL_DIR

PATH_IN_BACKTICKS = re.compile(r"`((?:\.\./)?(?:flows|references|scripts|assets|agents)/[A-Za-z0-9_./<>-]+)`")
PLACEHOLDER = re.compile(r"<[^>]+>")
HOME_PREFIX = "/" + "Users/"     # built at runtime so this file does not trip its own check


def flat(text):
    """Markdown is hard-wrapped, so a phrase check has to ignore line breaks
    and emphasis markers."""
    return re.sub(r"\s+", " ", text.replace("**", ""))


def read(*parts):
    with open(os.path.join(SKILL_DIR, *parts), "r", encoding="utf-8") as fh:
        return fh.read()


# Bulk captures of the live Webflow site are a local cache: they are gitignored
# (a complete map of the site does not belong in git) and regenerated by
# flows/onboard.md step 3 and the guard's snapshot step. The docs name them, so
# the link checks below allow them to be absent in a fresh clone. Everything
# else a doc points at must exist.
LOCAL_CACHE = re.compile(
    r"(?:^|/)(?:site-inventory\.(?:json|md)"
    r"|(?:pre|post)\.[A-Za-z0-9_.-]*\.?json"
    r"|[A-Za-z0-9_.-]*\.(?:pre|post)\.snapshot\.json)$"
)


def is_local_cache(raw):
    return bool(LOCAL_CACHE.search(raw))


def referenced_paths(text, base_dir):
    """Backticked skill paths in text, resolved against base_dir; placeholders skipped."""
    found = []
    for raw in PATH_IN_BACKTICKS.findall(text):
        if PLACEHOLDER.search(raw):
            continue                       # e.g. references/catalog/<family>.md
        found.append((raw, os.path.normpath(os.path.join(base_dir, raw))))
    return found


class SkillTreeTests(unittest.TestCase):
    def test_skill_md_frontmatter_and_size(self):
        text = read("SKILL.md")
        self.assertTrue(text.startswith("---\n"))
        fm = text.split("---\n", 2)[1]
        self.assertIsNotNone(re.search(r"^name: webflow-template$", fm, re.M), "name must match the directory name")
        self.assertIsNotNone(re.search(r"^disable-model-invocation: true$", fm, re.M))
        self.assertEqual(os.path.basename(SKILL_DIR), "webflow-template")
        lines = text.count("\n") + 1
        self.assertLess(lines, 500, f"SKILL.md is {lines} lines; the Agent Skills spec recommends under 500")

    def test_every_path_in_skill_md_exists(self):
        text = read("SKILL.md")
        refs = referenced_paths(text, SKILL_DIR)
        self.assertGreater(len(refs), 15, "SKILL.md should reference the flows, references, scripts, and assets")
        missing = [raw for raw, path in refs if not os.path.exists(path) and not is_local_cache(raw)]
        self.assertEqual(missing, [], f"SKILL.md points at paths that do not exist: {missing}")
        for required in ("flows/build.md", "flows/onboard.md", "flows/maintain.md", "flows/sync.md", "flows/resume.md",
                         "references/rules.md", "references/catalog/README.md", "references/runs/README.md",
                         "references/webflow-conventions.md", "references/examples/",
                         "scripts/validate_brief.py", "agents/openai.yaml", "CHANGELOG.md"):
            self.assertIn(f"`{required}`", text, f"SKILL.md should name {required}")
            self.assertTrue(os.path.exists(os.path.join(SKILL_DIR, required)), required)

    def test_every_path_in_flows_exists(self):
        flows_dir = os.path.join(SKILL_DIR, "flows")
        missing = []
        for name in sorted(os.listdir(flows_dir)):
            if not name.endswith(".md"):
                continue
            text = read("flows", name)
            for raw, path in referenced_paths(text, flows_dir):
                # `scripts/x.py` and `references/x` inside a flow are written relative to the skill root
                if is_local_cache(raw):
                    continue
                if not os.path.exists(path) and not os.path.exists(os.path.join(SKILL_DIR, raw)):
                    missing.append(f"{name}: {raw}")
        self.assertEqual(missing, [])

    def test_catalog_ships_empty_and_onboarding_is_documented(self):
        """The catalog is generated per site, so the shipped tree has none.

        A site inventory index is optional: onboarding may commit one, and when it
        does it must stay small, list components by name and group with no ids, and
        never carry the Bridge App launch link (rules.md rule 15).
        """
        import json
        catalog_dir = os.path.join(SKILL_DIR, "references", "catalog")
        entries = [name for name in sorted(os.listdir(catalog_dir))
                   if name.endswith(".md") and name.lower() != "readme.md"]
        self.assertEqual(entries, [], "references/catalog/ ships empty; flows/onboard.md writes it")
        skill_md = read("SKILL.md")
        self.assertIn("Onboarding comes first", skill_md)
        self.assertIn("`flows/onboard.md`", skill_md)
        self.assertIn("ships empty", read("references", "runs", "README.md"))

        index_path = os.path.join(SKILL_DIR, "references", "site-inventory.index.json")
        if not os.path.exists(index_path):
            return                       # nothing is committed before onboarding runs
        with open(index_path, "r", encoding="utf-8") as fh:
            index = json.load(fh)
        self.assertLess(os.path.getsize(index_path), 64 * 1024, "the index must stay small; it is not a site dump")
        for component in index.get("components", []):
            self.assertEqual(sorted(component), ["group", "name"],
                             "index components carry a name and a group, never an id")
        self.assertNotIn("launchLink", json.dumps(index), "the Bridge App link is a credential; keep it out of the index")

    def test_conventions_file_ships_as_an_unfilled_template(self):
        """webflow-conventions.md is a template: onboarding measures every row."""
        text = read("references", "webflow-conventions.md")
        self.assertIn("**This file is a template.", text)
        self.assertIn("MEASURE", text)
        self.assertIn("UNMEASURED", text)
        # the instruction prefix is defined exactly once, here, and defaults to page-templates
        self.assertIn("Instruction prefix", text)
        self.assertIn("`page-templates`", text)
        self.assertIn("**The one place this is defined.**", text)

    def test_example_tree_is_marked_as_an_example(self):
        for parts in (("references", "examples", "README.md"), ("assets", "examples", "README.md")):
            text = read(*parts)
            self.assertIn("fiction", text.lower(), parts)
        self.assertTrue(os.path.isfile(os.path.join(SKILL_DIR, "references", "examples", "catalog", "product-landing.md")))
        self.assertTrue(os.path.isfile(os.path.join(SKILL_DIR, "references", "examples", "webflow-conventions.md")))

    def test_versions_agree(self):
        fm = read("SKILL.md").split("---\n", 2)[1]
        skill_version = re.search(r'^\s+version:\s*"?([0-9]+\.[0-9]+\.[0-9]+)"?\s*$', fm, re.M)
        self.assertIsNotNone(skill_version, "SKILL.md metadata.version missing")
        changelog = read("CHANGELOG.md")
        top = re.search(r"^## \[([0-9]+\.[0-9]+\.[0-9]+)\]", changelog, re.M)
        self.assertIsNotNone(top, "CHANGELOG.md has no version heading")
        self.assertEqual(skill_version.group(1), top.group(1), "SKILL.md metadata.version and the CHANGELOG top section must agree")
        self.assertIn("### Known limitations", changelog)

    def test_bundle_has_no_bin_and_catalog_has_readme(self):
        plugin_root = os.path.dirname(os.path.dirname(SKILL_DIR))
        self.assertFalse(os.path.isdir(os.path.join(plugin_root, "bin")), "claude.ai rejects plugins with a top-level bin/; keep executables in scripts/")
        self.assertFalse(os.path.isdir(os.path.join(SKILL_DIR, "bin")))
        for folder in ("references/catalog", "references/catalog/candidates", "references/runs"):
            self.assertTrue(os.path.isfile(os.path.join(SKILL_DIR, folder, "README.md")), folder)

    # ---------------------------------------------- the public-exposure guarantee

    def test_skill_md_states_what_can_and_cannot_be_public(self):
        """The section is prominent, names every category, and does not soften
        the one category that is public immediately."""
        text = read("SKILL.md")
        self.assertIn("## What this can and cannot make public", text)
        section = text.split("## What this can and cannot make public", 1)[1].split("\n## ", 1)[0]
        for phrase in ("draft: true", "next site publish", "from the moment of upload",
                       "branch staging", "agent_instructions:read", "CMS items"):
            self.assertIn(phrase, flat(section), phrase)
        self.assertIn("publish_site", section)

    def test_rulebook_covers_public_exposure(self):
        rules = read("references", "rules.md")
        self.assertIn("Never call `publish_site`", rules)
        self.assertIn("19. **Public exposure", rules, "rule 19 is the public-exposure rule")
        rule19 = rules.split("19. **Public exposure", 1)[1]
        for phrase in ("from the moment of upload",
                       "does not un-serve a URL someone already has",
                       "ships-at-next-publish",
                       "redirects to the Webflow login and returns HTTP 403",
                       "CMS items are never a store"):
            self.assertIn(phrase, flat(rule19), phrase)
        # the count in SKILL.md must follow the rulebook
        numbers = [int(m) for m in re.findall(r"^(\d+)\. ", rules, re.M)]
        self.assertEqual(numbers, list(range(1, max(numbers) + 1)), "rules are numbered without gaps")
        self.assertIn(f"{max(numbers)} rules", read("SKILL.md"))

    def test_build_flow_warns_before_uploading_and_reports_uploads(self):
        build = read("flows", "build.md")
        self.assertIn("Before any `asset_tool > upload_image_by_url`, stop and warn", flat(build))
        self.assertIn("from the moment of upload", build)
        phase7 = build.split("## Phase 7", 1)[1]
        self.assertIn("Already public", phase7)
        self.assertLess(phase7.index("Already public"), phase7.index("Ships-at-next-publish"),
                        "the already-public line is reported before ships-at-next-publish")

    def test_phase6_normative_checklist_and_tracking_match(self):
        """Phase 6 names the checklist; Phase 7 prints it before ships-at-next-publish;
        builds match site tracking extras and ask before any deviation; rule 14
        still forbids page/site scripts."""
        build = read("flows", "build.md")
        self.assertIn("## Phase 6: Verify (normative checklist, readback not memory)", build)
        self.assertIn("### The normative checklist", build)
        for row_id in ("outline-match", "family-rules", "cta", "seo", "guard", "tracking"):
            self.assertIn(f"`{row_id}`", build, row_id)

        phase7 = build.split("## Phase 7", 1)[1]
        self.assertIn("normative checklist", flat(phase7))
        self.assertLess(phase7.lower().index("normative checklist"),
                        phase7.lower().index("ships-at-next-publish"),
                        "the checklist is reported before ships-at-next-publish")

        self.assertIn("do not invent extras the convention does not list", flat(build))
        self.assertIn("stop and ask in that same turn", flat(build))
        self.assertIn("measured convention", flat(build))

        rules = read("references", "rules.md")
        rule14 = rules.split("14. ", 1)[1].split("\n15. ", 1)[0]
        self.assertIn("No site scripts, no page scripts", rule14)
        self.assertIn("Never add a new tracking scheme", flat(rule14))

    # -------------------------------------------------- onboarding without a repo

    def test_onboard_offers_a_store_choice_with_a_403_fallback(self):
        onboard = read("flows", "onboard.md")
        self.assertIn("## 0. Choose the store", onboard)
        step0 = onboard.split("## 0. Choose the store", 1)[1].split("\n## ", 1)[0]
        for phrase in ("agent_instructions:read", "agent_instructions:write",
                       "Never retry a 403 in a loop", "256 KB",
                       "must never be written to the store",
                       "confirmation before each write"):
            self.assertIn(phrase, flat(step0), phrase)
        self.assertIn("removes that reviewer", flat(step0),
                      "the review trade-off is stated, not hidden")
        self.assertIn("## 10. Verify the store is not public (once per site)", onboard)
        self.assertIn("delete_instruction", onboard.split("## 10.", 1)[1])

    def test_onboard_and_sync_agree_on_the_store_layout(self):
        """Both flows describe one path layout; a new path has to be added to both."""
        store_paths = ("rules/<prefix>.md", "<prefix>/SKILL.md", "<prefix>/conventions.md",
                       "<prefix>/catalog/<family>.md", "<prefix>/candidates/<slug>.md",
                       "<prefix>/runs/<date>-<slug>.md")
        onboard, sync = read("flows", "onboard.md"), read("flows", "sync.md")
        for path in store_paths:
            self.assertIn(f"`{path}`", sync, f"sync.md must list {path}")
            self.assertIn(f"`{path}`", onboard, f"onboard.md must list {path}")
        found = set(re.findall(r"`((?:rules/)?<prefix>[A-Za-z0-9_<>./-]+)`", onboard))
        allowed = set(store_paths) | {
            "<prefix>/exposure-check.md",     # the throwaway the one-time check writes and deletes
            "<prefix>-catalog-bundle.json",   # a download filename, not a store path
        }
        # a folder form such as `<prefix>/runs/` stands for the paths under it
        unexpected = {p for p in found - allowed
                      if not (p.endswith("/") and any(s.startswith(p) for s in store_paths))}
        self.assertEqual(unexpected, set(), "onboard.md writes a path sync.md does not know about")

    def test_build_handles_no_store_and_no_catalog_bundle(self):
        build = read("flows", "build.md")
        phase0 = build.split("## Phase 0", 1)[1].split("## Phase 1", 1)[0]
        self.assertIn("Third case: no store readable and no catalog bundle attached", flat(phase0))
        self.assertIn("not a zip", phase0, "chat takes HTML, JSON and plain text, never a zip")
        self.assertIn("stops at Phase 3", flat(phase0), "say what is degraded")
        self.assertIn("`flows/onboard.md`", phase0)

    def test_maintain_covers_promotion_without_a_repository(self):
        maintain = read("flows", "maintain.md")
        self.assertIn("## Maintaining without a repository", maintain)
        section = maintain.split("## Maintaining without a repository", 1)[1]
        for phrase in ("update_instruction", "delete_instruction", "isDraft: false",
                       "no second reader"):
            self.assertIn(phrase, flat(section), phrase)

    def test_no_machine_specific_paths(self):
        offenders = []
        for dirpath, dirnames, filenames in os.walk(SKILL_DIR):
            dirnames[:] = [d for d in dirnames if d != "__pycache__"]
            for name in filenames:
                if not name.endswith((".md", ".py", ".json", ".yaml", ".html")):
                    continue
                path = os.path.join(dirpath, name)
                with open(path, "r", encoding="utf-8", errors="replace") as fh:
                    if HOME_PREFIX in fh.read():
                        offenders.append(os.path.relpath(path, SKILL_DIR))
        self.assertEqual(offenders, [], "the skill is distributed to other machines; use relative paths or <repo>")


if __name__ == "__main__":
    unittest.main()
